# Generated by Django 5.2.7 on 2025-10-01 14:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('start_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)], verbose_name='Начало работы (минуты от 00:00)')),
                ('end_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)], verbose_name='Конец работы (минуты от 00:00)')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_api.employee', verbose_name='Сотрудник/Мастер')),
            ],
            options={
                'verbose_name': 'Расписание Мастера',
                'verbose_name_plural': 'Расписания Мастеров',
                'unique_together': {('employee', 'day_of_week')},
            },
        ),
    ]
