# Generated by Django 5.2.7 on 2025-10-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0002_employeeschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='employees',
            field=models.ManyToManyField(related_name='services', to='booking_api.employee', verbose_name='Сотрудники, оказывающие услугу'),
        ),
    ]
